name: forestvpn_test
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.2
  get: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/icons/
     - assets/images/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: fonts/SFProDisplay-Light.ttf
          weight: 300
        - asset: fonts/SFProDisplay-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/SFProDisplay-Regular.ttf
        - asset: fonts/SFProDisplay-RegularItalic.ttf
          style: italic
        - asset: fonts/SFProDisplay-Medium.ttf
          weight: 500
        - asset: fonts/SFProDisplay-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/SFProDisplay-Semibold.ttf
          weight: 600
        - asset: fonts/SFProDisplay-SemiboldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/SFProDisplay-Bold.ttf
          weight: 700
        - asset: fonts/SFProDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/SFProDisplay-Black.ttf
          weight: 800
        - asset: fonts/SFProDisplay-BlackItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/SFProDisplay-Heavy.ttf
          weight: 900
        - asset: fonts/SFProDisplay-HeavyItalic.ttf
          weight: 900
          style: italic
